services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "11434:11434"
    volumes:
      - ./backend:/app/backend
    environment:
      - POSTGRES_URI="postgresql://postgres:9305*Elcon@db:5433/ml_tutor"

  db:
    image: postgres:13
    ports:
    - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 9305*Elcon
      POSTGRES_DB: ml_tutor